# -*- coding: utf-8 -*-
"""DEPLOY_1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RNg99QNG22nJ8VHG2953EMqw2MBRW8iL

#DEPLOYMENT

##CREAT_LOAD_PKL_FILE
"""

print("hello_world")
